package com.ozr.boot.dao;

import com.ozr.boot.dataObject.ItemStockDao;
import org.apache.ibatis.annotations.Param;

public interface ItemStockMapper {
    int decreaseStock(@Param("itemid") Integer itemId, @Param("amount") Integer amount);


    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item_stock
     *
     * @mbg.generated Tue Jun 29 14:47:18 CST 2021
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item_stock
     *
     * @mbg.generated Tue Jun 29 14:47:18 CST 2021
     */
    int insert(ItemStockDao record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item_stock
     *
     * @mbg.generated Tue Jun 29 14:47:18 CST 2021
     */
    int insertSelective(ItemStockDao record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item_stock
     *
     * @mbg.generated Tue Jun 29 14:47:18 CST 2021
     */
    ItemStockDao selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item_stock
     *
     * @mbg.generated Tue Jun 29 14:47:18 CST 2021
     */
    int updateByPrimaryKeySelective(ItemStockDao record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item_stock
     *
     * @mbg.generated Tue Jun 29 14:47:18 CST 2021
     */
    int updateByPrimaryKey(ItemStockDao record);

    ItemStockDao selectByItemId(Integer itemId);

}