package com.ozr.boot.dao;

import com.ozr.boot.dataObject.ItemDao;
import com.ozr.boot.dataObject.UserDao;
import org.apache.ibatis.annotations.Param;
import org.springframework.context.ApplicationContext;

import java.util.List;

public interface ItemDaoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_seckill_item
     *
     * @mbg.generated Tue Jun 29 14:47:18 CST 2021
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_seckill_item
     *
     * @mbg.generated Tue Jun 29 14:47:18 CST 2021
     */
    int insert(ItemDao record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_seckill_item
     *
     * @mbg.generated Tue Jun 29 14:47:18 CST 2021
     */
    int insertSelective(ItemDao record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_seckill_item
     *
     * @mbg.generated Tue Jun 29 14:47:18 CST 2021
     */
    ItemDao selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_seckill_item
     *
     * @mbg.generated Tue Jun 29 14:47:18 CST 2021
     */
    int updateByPrimaryKeySelective(ItemDao record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_seckill_item
     *
     * @mbg.generated Tue Jun 29 14:47:18 CST 2021
     */
    int updateByPrimaryKey(ItemDao record);


    List<ItemDao> listItem();

    void increaseSales(@Param("itemId")Integer itemId, @Param("amount") Integer amount);
}