package com.ozr.boot.dao;

import com.ozr.boot.dataObject.OrderDao;

public interface OrderDaoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_seckill_order
     *
     * @mbg.generated Wed Jun 30 13:36:24 CST 2021
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_seckill_order
     *
     * @mbg.generated Wed Jun 30 13:36:24 CST 2021
     */
    int insert(OrderDao record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_seckill_order
     *
     * @mbg.generated Wed Jun 30 13:36:24 CST 2021
     */
    int insertSelective(OrderDao record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_seckill_order
     *
     * @mbg.generated Wed Jun 30 13:36:24 CST 2021
     */
    OrderDao selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_seckill_order
     *
     * @mbg.generated Wed Jun 30 13:36:24 CST 2021
     */
    int updateByPrimaryKeySelective(OrderDao record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_seckill_order
     *
     * @mbg.generated Wed Jun 30 13:36:24 CST 2021
     */
    int updateByPrimaryKey(OrderDao record);
}