package com.ozr.boot.dao;

import com.ozr.boot.dataObject.PromoDao;

public interface PromoDaoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_promo
     *
     * @mbg.generated Wed Jun 30 20:45:03 CST 2021
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_promo
     *
     * @mbg.generated Wed Jun 30 20:45:03 CST 2021
     */
    int insert(PromoDao record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_promo
     *
     * @mbg.generated Wed Jun 30 20:45:03 CST 2021
     */
    int insertSelective(PromoDao record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_promo
     *
     * @mbg.generated Wed Jun 30 20:45:03 CST 2021
     */
    PromoDao selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_promo
     *
     * @mbg.generated Wed Jun 30 20:45:03 CST 2021
     */
    int updateByPrimaryKeySelective(PromoDao record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_promo
     *
     * @mbg.generated Wed Jun 30 20:45:03 CST 2021
     */
    int updateByPrimaryKey(PromoDao record);

    PromoDao selectByItemId(Integer itemId);
}