package com.ozr.boot.dao;

import com.ozr.boot.dataObject.SequenceDao;
import org.apache.ibatis.annotations.Param;

public interface SequenceDaoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sequence_info
     *
     * @mbg.generated Wed Jun 30 15:13:45 CST 2021
     */
    int deleteByPrimaryKey(String name);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sequence_info
     *
     * @mbg.generated Wed Jun 30 15:13:45 CST 2021
     */
    int insert(SequenceDao record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sequence_info
     *
     * @mbg.generated Wed Jun 30 15:13:45 CST 2021
     */
    int insertSelective(SequenceDao record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sequence_info
     *
     * @mbg.generated Wed Jun 30 15:13:45 CST 2021
     */
    SequenceDao selectByPrimaryKey(String name);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sequence_info
     *
     * @mbg.generated Wed Jun 30 15:13:45 CST 2021
     */
    int updateByPrimaryKeySelective(SequenceDao record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sequence_info
     *
     * @mbg.generated Wed Jun 30 15:13:45 CST 2021
     */
    int updateByPrimaryKey(SequenceDao record);


    SequenceDao getSequenceByName(@Param("name") String name);
}