package com.ozr.boot.dao;

import com.ozr.boot.dataObject.StockLogDao;

public interface StockLogDaoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stock_log
     *
     * @mbg.generated Thu Jul 08 14:14:07 CST 2021
     */
    int deleteByPrimaryKey(String stockLogId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stock_log
     *
     * @mbg.generated Thu Jul 08 14:14:07 CST 2021
     */
    int insert(StockLogDao record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stock_log
     *
     * @mbg.generated Thu Jul 08 14:14:07 CST 2021
     */
    int insertSelective(StockLogDao record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stock_log
     *
     * @mbg.generated Thu Jul 08 14:14:07 CST 2021
     */
    StockLogDao selectByPrimaryKey(String stockLogId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stock_log
     *
     * @mbg.generated Thu Jul 08 14:14:07 CST 2021
     */
    int updateByPrimaryKeySelective(StockLogDao record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stock_log
     *
     * @mbg.generated Thu Jul 08 14:14:07 CST 2021
     */
    int updateByPrimaryKey(StockLogDao record);
}