package com.ozr.boot.dao;

import com.ozr.boot.dataObject.UserPasswordDao;

public interface UserPasswordDaoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_password
     *
     * @mbg.generated Mon Jun 28 16:44:27 CST 2021
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_password
     *
     * @mbg.generated Mon Jun 28 16:44:27 CST 2021
     */
    int insert(UserPasswordDao record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_password
     *
     * @mbg.generated Mon Jun 28 16:44:27 CST 2021
     */
    int insertSelective(UserPasswordDao record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_password
     *
     * @mbg.generated Mon Jun 28 16:44:27 CST 2021
     */
    UserPasswordDao selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_password
     *
     * @mbg.generated Mon Jun 28 16:44:27 CST 2021
     */
    int updateByPrimaryKeySelective(UserPasswordDao record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_password
     *
     * @mbg.generated Mon Jun 28 16:44:27 CST 2021
     */
    int updateByPrimaryKey(UserPasswordDao record);

    UserPasswordDao selectByUserId(Integer id);
}