package com.ozr.boot.dao;

import com.ozr.boot.dataObject.UserDao;

public interface UserDaoMapper {



    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_seckill_user
     *
     * @mbg.generated Mon Jun 28 16:44:27 CST 2021
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_seckill_user
     *
     * @mbg.generated Mon Jun 28 16:44:27 CST 2021
     */
    int insert(UserDao record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_seckill_user
     *
     * @mbg.generated Mon Jun 28 16:44:27 CST 2021
     */
    int insertSelective(UserDao record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_seckill_user
     *
     * @mbg.generated Mon Jun 28 16:44:27 CST 2021
     */
    UserDao selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_seckill_user
     *
     * @mbg.generated Mon Jun 28 16:44:27 CST 2021
     */
    int updateByPrimaryKeySelective(UserDao record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_seckill_user
     *
     * @mbg.generated Mon Jun 28 16:44:27 CST 2021
     */
    int updateByPrimaryKey(UserDao record);


    UserDao selectByTelphone(String telphone);
}