package com.ozr.boot.dataObject;

public class ItemDao {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_seckill_item.id
     *
     * @mbg.generated Tue Jun 29 14:47:18 CST 2021
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_seckill_item.title
     *
     * @mbg.generated Tue Jun 29 14:47:18 CST 2021
     */
    private String title;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_seckill_item.price
     *
     * @mbg.generated Tue Jun 29 14:47:18 CST 2021
     */
    private Double price;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_seckill_item.description
     *
     * @mbg.generated Tue Jun 29 14:47:18 CST 2021
     */
    private String description;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_seckill_item.sales
     *
     * @mbg.generated Tue Jun 29 14:47:18 CST 2021
     */
    private Integer sales;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_seckill_item.imgurl
     *
     * @mbg.generated Tue Jun 29 14:47:18 CST 2021
     */
    private String imgurl;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_seckill_item.id
     *
     * @return the value of tbl_seckill_item.id
     *
     * @mbg.generated Tue Jun 29 14:47:18 CST 2021
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_seckill_item.id
     *
     * @param id the value for tbl_seckill_item.id
     *
     * @mbg.generated Tue Jun 29 14:47:18 CST 2021
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_seckill_item.title
     *
     * @return the value of tbl_seckill_item.title
     *
     * @mbg.generated Tue Jun 29 14:47:18 CST 2021
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_seckill_item.title
     *
     * @param title the value for tbl_seckill_item.title
     *
     * @mbg.generated Tue Jun 29 14:47:18 CST 2021
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_seckill_item.price
     *
     * @return the value of tbl_seckill_item.price
     *
     * @mbg.generated Tue Jun 29 14:47:18 CST 2021
     */
    public Double getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_seckill_item.price
     *
     * @param price the value for tbl_seckill_item.price
     *
     * @mbg.generated Tue Jun 29 14:47:18 CST 2021
     */
    public void setPrice(Double price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_seckill_item.description
     *
     * @return the value of tbl_seckill_item.description
     *
     * @mbg.generated Tue Jun 29 14:47:18 CST 2021
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_seckill_item.description
     *
     * @param description the value for tbl_seckill_item.description
     *
     * @mbg.generated Tue Jun 29 14:47:18 CST 2021
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_seckill_item.sales
     *
     * @return the value of tbl_seckill_item.sales
     *
     * @mbg.generated Tue Jun 29 14:47:18 CST 2021
     */
    public Integer getSales() {
        return sales;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_seckill_item.sales
     *
     * @param sales the value for tbl_seckill_item.sales
     *
     * @mbg.generated Tue Jun 29 14:47:18 CST 2021
     */
    public void setSales(Integer sales) {
        this.sales = sales;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_seckill_item.imgurl
     *
     * @return the value of tbl_seckill_item.imgurl
     *
     * @mbg.generated Tue Jun 29 14:47:18 CST 2021
     */
    public String getImgurl() {
        return imgurl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_seckill_item.imgurl
     *
     * @param imgurl the value for tbl_seckill_item.imgurl
     *
     * @mbg.generated Tue Jun 29 14:47:18 CST 2021
     */
    public void setImgurl(String imgurl) {
        this.imgurl = imgurl == null ? null : imgurl.trim();
    }
}