server:
  port: 8080 #端口设置

mybatis:
  mapper-locations: classpath:mybatis/mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true



spring:
  #数据连接需要的信息
  datasource:
    name: seckill
    username: root
    url: jdbc:mysql://localhost:3306/seckill?useUnicode=true&characterEncoding=UTF-8
    password: ou123456
#    url: jdbc:mysql://10.16.61.110:3306/seckill?useUnicode=true&characterEncoding=UTF-8

#    password: 123456

    # 数据源配置
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver

  mvc:
    throw-exception-if-no-handler-found: true
  web:
    resources:
          add-mappings: false

  #spring.mvc.throw-exception-if-no-handler-found=true
  #spring.resources.add-mappings=false





